// Command gen-desc extracts Go doc comments from frp's config structs and
// emits cmd/frp-manager/descriptions_gen.go, which the frp-manager schema
// generator uses as human-readable field descriptions.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	dirs := []string{"pkg/config/v1", "pkg/config/types"}
	out := map[string]string{}
	for _, dir := range dirs {
		entries, err := os.ReadDir(dir)
		if err != nil {
			panic(err)
		}
		for _, e := range entries {
			if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") || strings.HasSuffix(e.Name(), "_test.go") {
				continue
			}
			path := filepath.Join(dir, e.Name())
			fset := token.NewFileSet()
			f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
			if err != nil {
				panic(err)
			}
			for _, decl := range f.Decls {
				gd, ok := decl.(*ast.GenDecl)
				if !ok || gd.Tok != token.TYPE {
					continue
				}
				for _, spec := range gd.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					st, ok := ts.Type.(*ast.StructType)
					if !ok {
						continue
					}
					name := ts.Name.Name
					for _, field := range st.Fields.List {
						doc := field.Doc.Text()
						if doc == "" {
							doc = field.Comment.Text()
						}
						doc = clean(doc)
						if doc == "" {
							continue
						}
						for _, n := range field.Names {
							key := name + "." + n.Name
							out[key] = doc
						}
					}
				}
			}
		}
	}

	keys := make([]string, 0, len(out))
	for k := range out {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b bytes.Buffer
	b.WriteString("// Code generated by hack/gen-desc. DO NOT EDIT.\n\npackage main\n\n")
	b.WriteString("var fieldDescriptions = map[string]string{\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "\t%q: %q,\n", k, out[k])
	}
	b.WriteString("}\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		panic(err)
	}
	//nolint:gosec // generated Go source file, not sensitive data
	if err := os.WriteFile("cmd/frp-manager/descriptions_gen.go", formatted, 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("generated %d descriptions\n", len(out))
}

func clean(s string) string {
	lines := strings.Split(strings.TrimSpace(s), "\n")
	var out []string
	for _, l := range lines {
		l = strings.TrimSpace(l)
		if l == "" {
			continue
		}
		if strings.HasPrefix(l, "$") { // e.g. $HideFromDoc
			continue
		}
		out = append(out, l)
	}
	if len(out) == 0 {
		return ""
	}
	return strings.Join(out, " ")
}
